name: validate and push
on:
  push:
    branches:
      - main
jobs:
  validate-zip-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4
      - name: ğŸ” Validate Resource Pack
        uses: MrKinau/ResourcePackValidator@v1
        with:
          resourcepack: ./resources
          config: .github/workflows/validate-resource-pack-config.json
      - name: ğŸ‘‰ğŸ‘ˆ zip
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: resources/
          dest: resources.zip
      - name: ğŸ“‚ Deploy to Server
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-user: ${{ secrets.FTP_USERNAME }}
          remote-host: ${{ secrets.FTP_HOST }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-port: ${{ secrets.FTP_PORT }}
          local-path: './resources.zip'
          remote-path: '''/1. PaJo SMP/server/'''
      - name: ğŸ–¥ï¸ RCON Connection
        uses: Plagiatus/RCON-Action@v0.2
        with:
          server: ${{ secrets.RCON_IP }}
          port: ${{ secrets.RCON_PORT }}
          password: ${{ secrets.RCON_PASSWORD }}
          commands: '["reload", "pack set \"http://157.85.94.67:26314\" push"]'